[giscus]
    data-repo="Kyle-Derrick/Kyle-Derrick.github.io"
    data-repo-id="R_kgDOOqQLVA"
    data-category="Announcements"
    data-category-id="DIC_kwDOOqQLVM4CtPKE"
    data-mapping="pathname"
    data-strict="0"
    data-reactions-enabled="1"
    data-emit-metadata="0"
    data-input-position="bottom"
    data-theme="preferred_color_scheme"
    data-lang="zh-CN"
    crossorigin="anonymous"
