[giscus]
    data-repo="Kyle-Derrick/giscus-comments"
    data-repo-id="R_kgDOPQGMFw"
    data-category="Announcements"
    data-category-id="DIC_kwDOPQGMF84CtO_C"
    data-mapping="pathname"
    data-strict="0"
    data-reactions-enabled="1"
    data-emit-metadata="0"
    data-input-position="bottom"
    data-theme="preferred_color_scheme"
    data-lang="zh-CN"
    crossorigin="anonymous"
